- import_tasks: CentOS.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Check ruby Version
  shell: ruby -v
  register: ruby_ver
  notify: Ruby Version

