init_db: 
  # mysql:
  #   user: root
  #   password: 123456

  # postgrepsql:
  #   user: postgres
  #   password: ABCDEFG

  # mongodb:
  #   user: root
  #   password: mongodb_pass


init_application:
  # redmine: 
  #   service: redmine
  #   database: redmine
  #   database_user: redmine
  #   database_host: 127.0.0.1
  #   database_password: redmine
  #   default_account: admin
  #   default_password: admin
  #   random_password: True #True or False
  #   random_password_method: 
  #     - xxx/xxx/xxx
  #   config_path: 
  #     - /data/config/1.config


